from enum import Enum


class ErrorCode(str, Enum):
    COMMON_SUCCESS = "COMMON_SUCCESS"
    COMMON_NO_CONTENT = "COMMON_NO_CONTENT"
    COMMON_REQUEST_ERROR = "COMMON_REQUEST_ERROR"
    COMMON_INTERNAL_SERVER_ERROR = "COMMON_INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
